application:
    name: medicine
    port: 8081

jwt:
    expire: 8760
    secret: 2dd6917f09814627ab7d94c4e3532934

aes:
    secret: D0D1702422614BFAA0BD016FF5DF04AE

mysql:
    username: root
    password: 1qaz@WSX
    addr: 47.103.98.61
    port: 3306
    databases: medicine
    charset: utf8

huawei:
    oauth2_url: https://oauth-login.cloud.huawei.com/oauth2/v3/token
    client_id: 6917574951926710701
    client_secret: bfb5c934caca3ff6e2bfce36e955f0f521879b0a4961abd032ea6fca574efe4d
    account_url: https://account.cloud.huawei.com/rest.php?nsp_svc=GOpen.User.getInfo
